#  IMIGE/TCP, Copyright (C) 1995, IMIGE Systems Inc.
#
#  All rights reserved.
#  This software is under BSD license. see LICENSE.txt
#
#  Author : Minsuk Lee (ykhl1itj@gmail.com)
#
# This makefile need Borland C++ 3.1
#

.autodepend
.silent

SUFFIX = ccc

TC = C:\BORLANDC
TCDIR = $(TC)\BIN
TCLIB = $(TC)\LIB

#WORKDIR = C:\MSLEE\IMIGETCP
WORKDIR = ..
INC = -I$(WORKDIR)\INCLUDE -I$(WORKDIR)\LIBRARY
DEFINE =
COPTIONS = -c -mt -O2 -G -f- $(INC) $(DEFINE)
CC = $(TCDIR)\BCC

AOPTIONS = /t
ASM = $(TCDIR)\TASM

LIB = $(TCDIR)\TLIB

LINK = $(TCDIR)\TLINK

LIBS = debug.lib
OBJS1 = czero.obj isrs.obj kernel.obj misc.obj ip.obj socket.obj
OBJS2 = buffer.obj udp.obj timer.obj tcp.obj packet.obj
OBJ = czero isrs kernel misc packet ip socket buffer udp timer tcp

all : tcpip.com

tcpip.com : $(OBJS1) $(OBJS2) Makefile $(LIBS)
	$(LINK) /s /t $(OBJ), $*, w, $(LIBS) cs
	@dir $<

.c.obj :
	$(CC) $(COPTIONS) $<

.asm.obj :
	$(ASM) $(AOPTIONS) $*;

debug.lib : printf.obj dump.obj

.ccc.obj :
	$(CC) $(COPTIONS) $<
	$(LIB) debug -+ $*
	@if exist *.bak erase *.bak

clean :
	@if exist *.~*  erase *.~*
	@if exist *.obj erase *.obj
	@if exist *.map erase *.map
	@if exist *.exe erase *.exe
	@if exist *.com erase *.com
	@if exist *.lib erase *.lib
	@if exist *.bak erase *.bak
	@if exist *.lst erase *.lst
	@if exist xxx erase xxx
